### ISSUE TITLE
19 - Permitir que um usuário logado inscreva-se em um concurso aberto

### ISSUE THREAD

**Issue by dmarczal** [dmarczal/photo-contest#37]

**Comment by viniciusalonso** [comment]
@rehnan para o login, foi utilizada a gem [devise](https://github.com/plataformatec/devise). Quando for escrever os testes a gem oferece alguns helpers para ajudar https://github.com/plataformatec/devise#test-helpers

**Comment by eduartheinen** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

Método de autenticação do devise.

**Comment by dmarczal** [comment]
https://github.com/dmarczal/photo-contest/commit/2ebf8bb62759e3294006170eb0c114a2648a33ec

**Comment by dmarczal** [comment]
Melhorar as views e fazer os links na layout

**Comment by dmarczal** [comment]
https://gist.github.com/denmarkin/955767
