### ISSUE TITLE
 Instalar Devise

### ISSUE THREAD

**Issue by eduartheinen** [dmarczal/photo-contest#5]
Adicionar ao gemfile e instalar a gem Devise. Depois de instalada configurar de acordo com as instruções na página da gem no github https://github.com/plataformatec/devise.

**Comment by dmarczal** [comment]
Associar a task a uma história!

**Comment by dmarczal** [comment]
Lembre-se que a autenticação será pelo webservices

**Comment by eduartheinen** [comment]
DONE https://github.com/dmarczal/photo-contest/pull/32
Vou criar outra tarefa para implementar a autenticação pelo LDAP assim que ele esteja funcionando.
